"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"

# Configure GitHub integration
"pull_request_title": "chore: update translations from Crowdin"
"pull_request_labels": ["i18n", "crowdin"]

# Configure pre-translation settings
"settings": {
    "auto_substitution": true,
    # AI settings for future use
    # "ai_pretranslate": true,
    # "ai_pretranslate_approve": false # Require human review of AI translations
  }

"files": [
    # Documentation content - MD files
    {
      "source": "src/content/docs/**/*.md",
      "translation": "src/content/docs/%two_letters_code%/**/%original_file_name%",
      "type": "md",
      "labels": ["documentation"],
      "update_option": "update_as_unapproved",
      "mt_engine": "deepl",
    },
    # Documentation content - MDX files
    {
      "source": "src/content/docs/**/*.mdx",
      "translation": "src/content/docs/%two_letters_code%/**/%original_file_name%",
      "type": "md",
      "labels": ["documentation"],
      "update_option": "update_as_unapproved",
      "mt_engine": "deepl",
    },
    # i18n JSON files
    {
      "source": "src/content/i18n/en.json",
      "translation": "src/content/i18n/%two_letters_code%.json",
      "type": "json",
      "labels": ["ui-strings"],
      "update_option": "update_as_unapproved",
      # AI configuration for future use
      # "ai_pretranslate": {
      #   "engine": "crowdin-ai",
      #   "label": "ai-generated"
      # }
      "mt_engine": "deepl",
    },
  ]
