[package]
name = "fix-i18n-links"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
walkdir = "2.4"
colored = "2.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"